apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-service
  name: location-service
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: location-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-service
  name: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-service
  template:
    metadata:
      labels:
        service: location-service
    spec:
      containers:
      - image: mhaikel/location-service:latest
        name: location-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always