apiVersion: v1
kind: Service
metadata:
  labels:
    service: location-event-consumer
  name: location-event-consumer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    service: location-event-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location-event-consumer
  name: location-event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-event-consumer
  template:
    metadata:
      labels:
        service: location-event-consumer
    spec:
      containers:
      - image: mhaikel/location-event-consumer:latest
        name: location-event-consumer
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always